### ISSUE TITLE
Cannot post due to 4chan changing their Captcha/re-captcha

### ISSUE THREAD

**Issue by ChrisPYP** [SuperGouge/ST4ImageDumper#1]
Hi, new here. just wanted to notify you that I can't use this to post anymore due to 4chan changing their capcha/re-captcha again.

this is the txt file feedback i get when i try to post.

System.Exception: Unable to find a text field named "recaptcha_challenge_field".
   at JDP.ExtensionMethods.GetTextField(List`1 list, String name) in e:\Stuff\Code\ST4ImageDumper\Classes\Other.cs:line 11
   at JDP.ImageDumper.DumpThread() in e:\Stuff\Code\ST4ImageDumper\Classes\ImageDumper.cs:line 490

Glad someone decided to take over where it got left off.

**Comment by SuperGouge** [comment]
I'm afraid that to support the new reCAPTCHA API, a substantial amount of changes are to be done. Unfortunately, this API is relatively new and I'll have to have a closer look at it before knowing how to handle it. I'll try whenever I get the chance but no promises, sorry.

**Comment by ipatrol** [comment]
Any progress on this? There is, at the moment, literally NO dump program/script that works with 4chan, as far as I can tell.

**Comment by SuperGouge** [comment]
No progress but I think [4chan X](https://github.com/ccd0/4chan-x) has what you're looking for.

**Comment by ChrisPYP** [comment]
https://github.com/ccd0/4chan-x

is what I've been using, which works with new captcha/old captcha

thanks

-----Original Message-----

**Comment by ChrisPYP** [comment]
this is exactly what i have been using, thank you for the reply :)

-----Original Message-----
